name: donut
dependencies:
  - python=3.7
  - pip
  - pip:
      - git+https://github.com/thu-ml/zhusuan.git
      - git+https://github.com/haowen-xu/tfsnippet.git@v0.1.2
  - scikit-learn
  - tensorflow-gpu=1.15
  - pandas
